import {
  type BuildMocksOptions,
  type MockResult,
  buildMocks,
} from '@vantreeseba/graphql-mocks';
import type { GraphQLSchema } from 'graphql';
import type { SchemaTypeMap } from '../../__generated__/schema-type-map.ts';

// Defaults that keep mock output deterministic and readable. The schema's only
// custom scalar is DateTime, mocked as an ISO timestamp.
const DEFAULTS: BuildMocksOptions = {
  seed: 42,
  stableIds: true,
  scalars: {
    DateTime: (faker) => faker.date.recent().toISOString(),
  },
};

// Typed mock pools for the app schema. The `SchemaTypeMap` generated by
// @vantreeseba/graphql-mocks-codegen gives `mocks.User`, `mocks.Note`, etc.
// their real types (User[], Note[], …) with no cast.
export function buildSchemaMocks(
  schema: GraphQLSchema,
  options: BuildMocksOptions = {},
): MockResult<SchemaTypeMap> {
  return buildMocks<SchemaTypeMap>(schema, { ...DEFAULTS, ...options });
}
